using MediatR;
using SproutVRSchool.Application.Commons.Responses;

namespace SproutVRSchool.Application.RequestHandlers.Authorized.VRDeviceSessionSummaries.Queries.SearchVRDeviceSessionSummaries;

public sealed record AuthorizedSearchVRDeviceSessionSummariesQuery(
    AuthorizedSearchVRDeviceSessionSummariesQueryParams Params
) : IRequest<GetListResultResponseDto<AuthorizedSearchVRDeviceSessionSummariesQueryResponseDto>>;
