<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="..\SproutVRSchool.Domain\SproutVRSchool.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
		<PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
		<PackageReference Include="MediatR" Version="13.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Commons\Requests\" />
		<Folder Include="Extensions\" />
	</ItemGroup>

	<ItemGroup>
		<Protobuf Include="Commons\Protos\learning_session.proto" GrpcServices="Server" />
	</ItemGroup>

</Project>
