<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Folder Include="Entities\MapObjects\" />
    <Folder Include="Entities\Maps\" />
    <Folder Include="Entities\Subjects\" />
    <Folder Include="Entities\ObjectActivityTypes\" />
    <Folder Include="Entities\TaskLocations\" />
    <Folder Include="Exceptions\" />
  </ItemGroup>
</Project>
