<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="..\SproutVRSchool.Application\SproutVRSchool.Application.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Extensions\" />
		<Folder Include="Database\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
	</ItemGroup>

</Project>
