syntax = "proto3";

package LearningSession.v1;

import "google/protobuf/timestamp.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/empty.proto";

// ================================================================
// === TeacherSessionManagement
// ================================================================

service TeacherSessionManagement {
  // Teacher - Game Server: 
  // - Create new learing session but not started yet
  rpc CreateRoom(CreateRoomRequest) returns (CreateRoomResponse);

  // Teacher - Game Server: 
  // - Set duration, start time, assign devices, and change status to Active
  rpc ActivateRoom(ActivateRoomRequest) returns (ActivateRoomResponse);

  // Teacher - Game Server: 
  // - Cancel the learning session
  rpc CancelRoom(CancelRoomRequest) returns (CancelRoomResponse);

  // Teacher - Game Server:
  // - Send commands to the server
  rpc SendNotification(SendNotificationRequest) returns (google.protobuf.Empty);
}

// ------------------------ CreateRoom --------------------
message CreateRoomRequest {
  string teacher_id = 1;
  string vr_lesson_id = 2;
  string class_name = 3;
}

message CreateRoomResponse {
  string vr_learning_session_id = 1;
}

// ------------------------ ActivateRoom -------------------
message ActivateRoomRequest {
  string vr_learning_session_id = 1;
  google.protobuf.Timestamp start_time_at_utc = 2;
  google.protobuf.Duration duration_in_minutes = 3;
  repeated string assigned_device_serials = 4;  // list of device allowed to join
}

message ActivateRoomResponse {
  string room_code = 1;                         // The join code is generated and returned here.
}

// ------------------------ JoinRoom ------------------------
message JoinRoomRequest {
  string room_code = 1;
  string vr_device_serial_number = 2;
  string vr_device_name = 3;
}

message JoinRoomResponse {
  enum JoinStatus {
    JOIN_STATUS_UNSPECIFIED = 0;    // default value for switch-case when client consumes it
    SUCCESS = 1;
    INVALID_ROOM_CODE = 2;          // room code doesn't exist
    ROOM_NOT_ACTIVE = 3;            // room not yet active, still in pending, completed, or cancelled
    DEVICE_NOT_AUTHORIZED = 4;      // device connect but not in the assigned list, so not authorized
    ALREADY_JOINED = 5;             // device already joined before, stop rejoining
  }
  JoinStatus status = 1;
  string message = 2;
  string vr_learning_session_id = 3;
  string preset_json_content = 4;
}

// ------------------------ CancelRoom ------------------------
message CancelRoomRequest {
  string vr_learning_session_id = 1;
}

message CancelRoomResponse {
  string message = 1;
}

// ------------------------ SendNotification -------------------
message SendNotificationRequest {
  string vr_learning_session_id = 1;
  NotificationSignal notification = 2;
}

// ================================================================
// === VRGlassSessionManagement
// ================================================================

service VRGlassSessionManagement {
  // VR Glasses - Game Server: 
  // - Join the learning session via room code
  rpc JoinRoom(JoinRoomRequest) returns (JoinRoomResponse);

  // VR Glasses - Game Server
  // - receive stats from VR device, send signals or any message from server to VR glasses
  rpc StreamSessionState(stream ClientToServerMessage) returns (stream ServerToClientMessage);
}

// ------------------------ StreamSessionState ------------------------
message ClientToServerMessage {
  string vr_learning_session_id = 1;
  string vr_device_serial_number = 2;
  
  oneof payload {
    TaskUpdate task_update = 3;
  }
}

message TaskUpdate {
  string vr_task_id = 1;
  bool is_completed = 2;
  bool is_correct = 3;
}

message ServerToClientMessage {
  oneof payload {
    UpdateTaskSignal task_signal = 1;    // If sending this, task data is updated in the server
    EndSessionSignal end_signal = 2;     // If sending this, VR Glasses game is stop
    NotificationSignal notification = 3; // If sending this, could be info or warning
  }
}

message UpdateTaskSignal {
  enum TaskStatus {
    TASK_STATUS_UNSPECIFIED = 0; // Unexpected server error
    SUCCESS = 1;                 // Task updated successfully
    UPDATE_FAILED = 2;           // Logical/Contraint error in the server
  }
  
  string message = 1;
  TaskStatus status = 2;
}

message NotificationSignal {
  enum Severity {
    INFO = 0;
    WARNING = 1;
  }
  
  string text = 1;
  Severity severity = 2;
}

message EndSessionSignal {
  string reason = 1;        // Ví dụ: "Hết giờ" hoặc "Giáo viên đã kết thúc buổi học"
}







