syntax = "proto3";

package LearningSession.v1;

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";

// ================================================================
// === Teacher Real-Time State Session Monitor
// ================================================================

service TeacherSessionRealTimeStateManagement {

  // Teacher - Game Server:
  // - Receive the initial room's state
  rpc GetRoomState(GetRoomStateRequest) returns (GetRoomStateResponse);

  // Teacher - Game Server:
  // - Server sends room's state to the Desktop client app
  rpc StreamTeacherRoomState(TeacherRoomStreamRequest) returns (stream TeacherRoomUpdateResponse);
}

// ------------------------ CreateRoom --------------------

message GetRoomStateRequest {
  string vr_learning_session_id = 1;
}

message GetRoomStateResponse {
  string json_state = 1; 
}

// ------------------------ StreamTeacherRoomState ------------------------

message TeacherRoomStreamRequest {
  string vr_learning_session_id = 1;
}

message TeacherRoomUpdateResponse {
  string vr_learning_session_id = 1;

  oneof payload {
    RoomCreated room_created = 2;
    RoomActivated room_activated = 3;
    RoomCancelled room_cancelled = 4;
    RoomEnded room_ended = 5;
    DeviceJoined device_joined = 6;
    DeviceDisconnected device_disconnected = 7;
    TaskUpdated task_updated = 8;
  }
}

message RoomCreated {
  string teacher_id = 1;                
  string vr_lesson_id = 2;              
  string class_name = 3;               
  string status = 4;                    
}

message RoomActivated {
  string room_code = 1;                          
  google.protobuf.Timestamp start_time_at_utc = 2; 
  int32 duration_in_seconds = 3;                   
}

message RoomCancelled {
  string cancelled_by = 1;   
  string reason = 2;         
}

message RoomEnded {
  string ended_by = 1;                  // teacher_id or system (timeout)
  string reason = 2;          
  google.protobuf.Timestamp end_time_at_utc = 3;
}

message DeviceJoined {
  string vr_device_serial_number = 1;   // Unique device serial
  string student_name = 2;              // Student using the device
  string connection_status = 3;         // "Connected"
}

message DeviceDisconnected {
  string vr_device_serial_number = 1;
  string student_name = 2;              
  string connection_status = 3;         // "Disconnected"
}

message TaskUpdated {
  string vr_device_serial_number = 1; 
  string vr_task_id = 2;               
  bool is_completed = 3;               
  bool is_correct = 4;                 
}

// ================================================================
// === Teacher Session Actions
// ================================================================

service TeacherSessionManagement {
  // Teacher - Game Server: 
  // - Create new learing session but not started yet
  rpc CreateRoom(CreateRoomRequest) returns (CreateRoomResponse);

  // Teacher - Game Server: 
  // - Set duration, start time, assign devices, and change status to Active
  rpc ActivateRoom(ActivateRoomRequest) returns (ActivateRoomResponse);

  // Teacher - Game Server: 
  // - Cancel the learning session
  rpc CancelRoom(CancelRoomRequest) returns (CancelRoomResponse);

  // Teacher - Game Server:
  // - Send commands to the server
  rpc SendNotification(SendNotificationRequest) returns (google.protobuf.Empty);

}

// ------------------------ CreateRoom --------------------

message CreateRoomRequest {
  string teacher_id = 1;
  string vr_lesson_id = 2;
  string class_name = 3;
}

message CreateRoomResponse {
  string vr_learning_session_id = 1;
}

// ------------------------ ActivateRoom -------------------

message ActivateRoomRequest {
  string vr_learning_session_id = 1;
  string vr_lesson_id = 2;
  google.protobuf.Timestamp start_time_at_utc = 3;
  repeated AssignedDevice assigned_device_serials = 4;  // list of device allowed to join
}

message ActivateRoomResponse {
  string room_code = 1;                                 // The join code is generated and returned here.
}

message AssignedDevice {
    string vr_device_serial_number = 1;
    string student_name = 2;
}

// ------------------------ JoinRoom ------------------------

message JoinRoomRequest {
  string room_code = 1;
  string vr_device_serial_number = 2;
}

message JoinRoomResponse {
  enum JoinStatus {
    JOIN_STATUS_UNSPECIFIED = 0;    // default value for switch-case when client consumes it
    SUCCESS = 1;
    INVALID_ROOM_CODE = 2;          // room code doesn't exist
    ROOM_NOT_ACTIVE = 3;            // room not yet active, still in pending, completed, or cancelled
    DEVICE_NOT_AUTHORIZED = 4;      // device connect but not in the assigned list, so not authorized
    ALREADY_JOINED = 5;             // device already joined before, stop rejoining
  }
  JoinStatus status = 1;
  string message = 2;
  string vr_learning_session_id = 3;
  string preset_json_content = 4;
}

// ------------------------ CancelRoom ------------------------

message CancelRoomRequest {
  string vr_learning_session_id = 1;
}

message CancelRoomResponse {
  string message = 1;
}

// ------------------------ SendNotification -------------------

message SendNotificationRequest {
  string vr_learning_session_id = 1;
  NotificationSignal notification = 2;
}

// ================================================================
// === VRGlassSessionManagement
// ================================================================

service VRGlassSessionManagement {
  // VR Glasses - Game Server: 
  // - Join the learning session via room code
  rpc JoinRoom(JoinRoomRequest) returns (JoinRoomResponse);

  // VR Glasses - Game Server
  // - receive stats from VR device, send signals or any message from server to VR glasses
  rpc StreamSessionState(stream ClientToServerMessage) returns (stream ServerToClientMessage);
}

// ------------------------ StreamSessionState ------------------------

message ClientToServerMessage {
  string vr_learning_session_id = 1;
  string vr_device_serial_number = 2;
  
  oneof payload {
    TaskUpdate task_update = 3;
  }
}

message TaskUpdate {
  string vr_task_id = 1;
  bool is_completed = 2;
  bool is_correct = 3;
}

message ServerToClientMessage {
  oneof payload {
    UpdateTaskSignal task_signal = 1;    // If sending this, task data is updated in the server
    EndSessionSignal end_signal = 2;     // If sending this, VR Glasses game is stop
    NotificationSignal notification = 3; // If sending this, could be info or warning
  }
}

message UpdateTaskSignal {
  enum TaskStatus {
    TASK_STATUS_UNSPECIFIED = 0; // Unexpected server error
    SUCCESS = 1;                 // Task updated successfully
    UPDATE_FAILED = 2;           // Logical/Contraint error in the server
  }
  
  string message = 1;
  TaskStatus status = 2;
}

message NotificationSignal {
  enum Severity {
    INFO = 0;
    WARNING = 1;
  }
  
  string text = 1;
  Severity severity = 2;
}

message EndSessionSignal {
  string reason = 1;        // Ví dụ: "Hết giờ" hoặc "Giáo viên đã kết thúc buổi học"
}