// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SproutVRSchool.Infrastructure.Data;

#nullable disable

namespace SproutVRSchool.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SchoolServerDbContext))]
    partial class SchoolServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("auth")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "auth");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.ActivityTypes.ActivityType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("Id");

                    b.ToTable("ActivityTypes", "app");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.Identities.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("UserAccounts", "auth");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.Identities.UserAccountRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", "auth");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.Lessons.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("citext");

                    b.Property<string>("ResourceRelativeFilePath")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Lessons", "app");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.MapObjects.MapObject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("citext");

                    b.Property<string>("ObjectCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.ToTable("MapObjects", "app");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.Maps.Map", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MapCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("citext");

                    b.Property<string>("PreviewUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Maps", "app");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.MasterSubjects.MasterSubject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("citext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("Id");

                    b.ToTable("MasterSubjects", "app");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.ObjectActivityTypes.ObjectActivityType", b =>
                {
                    b.Property<Guid>("MapObjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("MapObjectId", "ActivityTypeId");

                    b.HasIndex("ActivityTypeId");

                    b.ToTable("ObjectActivityTypes", "app");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.ObjectLocations.ObjectLocation", b =>
                {
                    b.Property<Guid>("TaskLocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("TaskLocationId", "ObjectId");

                    b.HasIndex("ObjectId");

                    b.ToTable("ObjectLocations", "app");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.Subjects.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("MasterSubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("citext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("Id");

                    b.HasIndex("MasterSubjectId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Subjects", "app");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.TaskLocations.TaskLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.ToTable("TaskLocations", "app");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.VRDeviceSessionSummaries.VRDeviceSessionSummary", b =>
                {
                    b.Property<Guid>("VRLearningSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VRDeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<int>("NoTasksCompleted")
                        .HasColumnType("integer");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("VRLearningSessionId", "VRDeviceId");

                    b.HasIndex("VRDeviceId");

                    b.ToTable("VRDeviceSessionSummaries", "app");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.VRDeviceTaskProgresses.VRDeviceTaskProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletionTimeAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsCorrect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<Guid>("VRDeviceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VRLearningSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VRTaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VRDeviceId");

                    b.HasIndex("VRLearningSessionId");

                    b.HasIndex("VRTaskId");

                    b.ToTable("VRDeviceTaskProgresses", "app");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.VRDevices.VRDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("citext");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("citext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("VRDevices", "app");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.VRLearningSessions.VRLearningSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<Guid>("VRLessonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.HasIndex("VRLessonId");

                    b.ToTable("VRLearningSessions", "app");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.VRLessons.VRLesson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("text");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("MaxDuration")
                        .HasColumnType("interval");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("citext");

                    b.Property<string>("PresetJsonRelativeFilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("MapId");

                    b.ToTable("VRLessons", "app");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.VRTasks.VRTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<Guid>("MapObjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("text");

                    b.Property<Guid>("TaskLocationId")
                        .HasColumnType("uuid");

                    b.Property<int>("TaskNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<Guid>("VRLessonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActivityTypeId");

                    b.HasIndex("MapObjectId");

                    b.HasIndex("TaskLocationId");

                    b.HasIndex("VRLessonId");

                    b.ToTable("VRTasks", "app");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.Identities.SchoolAdmin", b =>
                {
                    b.HasBaseType("SproutVRSchool.Domain.Entities.Identities.UserAccount");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasIndex("OrganizationId");

                    b.ToTable("SchoolAdmins", "auth");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.Identities.Teacher", b =>
                {
                    b.HasBaseType("SproutVRSchool.Domain.Entities.Identities.UserAccount");

                    b.ToTable("Teachers", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("SproutVRSchool.Domain.Entities.Identities.UserAccountRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SproutVRSchool.Domain.Entities.Identities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SproutVRSchool.Domain.Entities.Identities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("SproutVRSchool.Domain.Entities.Identities.UserAccountRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SproutVRSchool.Domain.Entities.Identities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SproutVRSchool.Domain.Entities.Identities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.Lessons.Lesson", b =>
                {
                    b.HasOne("SproutVRSchool.Domain.Entities.Subjects.Subject", "Subject")
                        .WithMany("Lessons")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SproutVRSchool.Domain.Entities.Identities.Teacher", "Teacher")
                        .WithMany("Lessons")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.MapObjects.MapObject", b =>
                {
                    b.HasOne("SproutVRSchool.Domain.Entities.Maps.Map", "Map")
                        .WithMany("MapObjects")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Map");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.Maps.Map", b =>
                {
                    b.HasOne("SproutVRSchool.Domain.Entities.Subjects.Subject", "Subject")
                        .WithMany("Maps")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.ObjectActivityTypes.ObjectActivityType", b =>
                {
                    b.HasOne("SproutVRSchool.Domain.Entities.ActivityTypes.ActivityType", "ActivityType")
                        .WithMany("ObjectActivityTypes")
                        .HasForeignKey("ActivityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SproutVRSchool.Domain.Entities.MapObjects.MapObject", "MapObject")
                        .WithMany("ObjectActivityTypes")
                        .HasForeignKey("MapObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActivityType");

                    b.Navigation("MapObject");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.ObjectLocations.ObjectLocation", b =>
                {
                    b.HasOne("SproutVRSchool.Domain.Entities.MapObjects.MapObject", "MapObject")
                        .WithMany("ObjectLocations")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SproutVRSchool.Domain.Entities.TaskLocations.TaskLocation", "TaskLocation")
                        .WithMany("ObjectLocations")
                        .HasForeignKey("TaskLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MapObject");

                    b.Navigation("TaskLocation");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.Subjects.Subject", b =>
                {
                    b.HasOne("SproutVRSchool.Domain.Entities.MasterSubjects.MasterSubject", "MasterSubject")
                        .WithMany("Subjects")
                        .HasForeignKey("MasterSubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MasterSubject");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.TaskLocations.TaskLocation", b =>
                {
                    b.HasOne("SproutVRSchool.Domain.Entities.Maps.Map", "Map")
                        .WithMany("TaskLocations")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Map");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.VRDeviceSessionSummaries.VRDeviceSessionSummary", b =>
                {
                    b.HasOne("SproutVRSchool.Domain.Entities.VRDevices.VRDevice", "VRDevice")
                        .WithMany("VRDeviceSessionSummaries")
                        .HasForeignKey("VRDeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SproutVRSchool.Domain.Entities.VRLearningSessions.VRLearningSession", "VRLearningSession")
                        .WithMany("VRDeviceSessionSummaries")
                        .HasForeignKey("VRLearningSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VRDevice");

                    b.Navigation("VRLearningSession");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.VRDeviceTaskProgresses.VRDeviceTaskProgress", b =>
                {
                    b.HasOne("SproutVRSchool.Domain.Entities.VRDevices.VRDevice", "VRDevice")
                        .WithMany("VRDeviceTaskProgresses")
                        .HasForeignKey("VRDeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SproutVRSchool.Domain.Entities.VRLearningSessions.VRLearningSession", "VRLearningSession")
                        .WithMany("VRDeviceTaskProgresses")
                        .HasForeignKey("VRLearningSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SproutVRSchool.Domain.Entities.VRTasks.VRTask", "VRTask")
                        .WithMany("DeviceTaskProgresses")
                        .HasForeignKey("VRTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VRDevice");

                    b.Navigation("VRLearningSession");

                    b.Navigation("VRTask");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.VRLearningSessions.VRLearningSession", b =>
                {
                    b.HasOne("SproutVRSchool.Domain.Entities.Identities.Teacher", "Teacher")
                        .WithMany("VRLearningSessions")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SproutVRSchool.Domain.Entities.VRLessons.VRLesson", "VRLesson")
                        .WithMany("VRLearningSessions")
                        .HasForeignKey("VRLessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Teacher");

                    b.Navigation("VRLesson");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.VRLessons.VRLesson", b =>
                {
                    b.HasOne("SproutVRSchool.Domain.Entities.Lessons.Lesson", "Lesson")
                        .WithMany("VRLessons")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SproutVRSchool.Domain.Entities.Maps.Map", "Map")
                        .WithMany()
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Map");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.VRTasks.VRTask", b =>
                {
                    b.HasOne("SproutVRSchool.Domain.Entities.ActivityTypes.ActivityType", "ActivityType")
                        .WithMany("VRTasks")
                        .HasForeignKey("ActivityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SproutVRSchool.Domain.Entities.MapObjects.MapObject", "MapObject")
                        .WithMany("VRTasks")
                        .HasForeignKey("MapObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SproutVRSchool.Domain.Entities.TaskLocations.TaskLocation", "TaskLocation")
                        .WithMany("VRTasks")
                        .HasForeignKey("TaskLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SproutVRSchool.Domain.Entities.VRLessons.VRLesson", "VRLesson")
                        .WithMany("VRTasks")
                        .HasForeignKey("VRLessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActivityType");

                    b.Navigation("MapObject");

                    b.Navigation("TaskLocation");

                    b.Navigation("VRLesson");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.Identities.SchoolAdmin", b =>
                {
                    b.HasOne("SproutVRSchool.Domain.Entities.Identities.UserAccount", null)
                        .WithOne()
                        .HasForeignKey("SproutVRSchool.Domain.Entities.Identities.SchoolAdmin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.Identities.Teacher", b =>
                {
                    b.HasOne("SproutVRSchool.Domain.Entities.Identities.UserAccount", null)
                        .WithOne()
                        .HasForeignKey("SproutVRSchool.Domain.Entities.Identities.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.ActivityTypes.ActivityType", b =>
                {
                    b.Navigation("ObjectActivityTypes");

                    b.Navigation("VRTasks");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.Lessons.Lesson", b =>
                {
                    b.Navigation("VRLessons");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.MapObjects.MapObject", b =>
                {
                    b.Navigation("ObjectActivityTypes");

                    b.Navigation("ObjectLocations");

                    b.Navigation("VRTasks");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.Maps.Map", b =>
                {
                    b.Navigation("MapObjects");

                    b.Navigation("TaskLocations");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.MasterSubjects.MasterSubject", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.Subjects.Subject", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("Maps");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.TaskLocations.TaskLocation", b =>
                {
                    b.Navigation("ObjectLocations");

                    b.Navigation("VRTasks");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.VRDevices.VRDevice", b =>
                {
                    b.Navigation("VRDeviceSessionSummaries");

                    b.Navigation("VRDeviceTaskProgresses");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.VRLearningSessions.VRLearningSession", b =>
                {
                    b.Navigation("VRDeviceSessionSummaries");

                    b.Navigation("VRDeviceTaskProgresses");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.VRLessons.VRLesson", b =>
                {
                    b.Navigation("VRLearningSessions");

                    b.Navigation("VRTasks");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.VRTasks.VRTask", b =>
                {
                    b.Navigation("DeviceTaskProgresses");
                });

            modelBuilder.Entity("SproutVRSchool.Domain.Entities.Identities.Teacher", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("VRLearningSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
