<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<UserSecretsId>9735d792-d272-46e4-a91a-c35732ae1141</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Controllers\Teacher\v1\FilesController.cs" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SproutVRSchool.Application\SproutVRSchool.Application.csproj" />
		<ProjectReference Include="..\SproutVRSchool.Infrastructure\SproutVRSchool.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Controllers\Auth\" />
	</ItemGroup>

</Project>
